<?php
/**
 * Created by PhpStorm.
 * User: zhangxiang
 * Date: 2018/10/19
 * Time: 下午6:04
 */

namespace app\admin\controller;


use think\App;
use think\Controller;
use think\facade\Session;

class BaseAdmin extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->checkAuth();
    }

    protected function checkAuth(){
        if (!Session::has('admin')) {
            $this->redirect('admin/login/index');
        }
    }
}